### ISSUE TITLE
Grid size and files

### ISSUE THREAD

**Issue by Jeremy643** [JeremyScott17/Coding-Challenges#6]
1. In the library, make it easier to change the size of the graph, possibly by implementing a slider.
2. Remove the index file and combine the sketch.js and cell.js into one file.

**Comment by JeremyScott17** [comment]
51132d53f0c355a5c135520cdbc96c90260a20de

**Comment by Jeremy643** [comment]
This issue was solved in commit 51132d53f0c355a5c135520cdbc96c90260a20de. Adjustments were made to the original plan but it remains a modular piece of code that allows users to easily create a grid on their screen.
